### ISSUE TITLE
Use env variable for Graasp Builder

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp-library#183]
Remove this line https://github.com/graasp/graasp-library/blob/747475517df7356a07f7035165d23b43556070c1/src/config/constants.js#L49
And refactor accordingly.

**Comment by IamGuneet** [comment]
Hey , can i do this?
@pyphilia

**Comment by pyphilia** [comment]
@IamGuneet Sure! The project should run even without the API, it just won't show any content.

The new variable to use is this one! https://github.com/graasp/graasp-library/blob/747475517df7356a07f7035165d23b43556070c1/src/config/constants.js#L4

**Comment by IamGuneet** [comment]
@pyphilia 
okay so i delete
line 49 

export const GRAASP_BUILDER_URL = 'https://builder.graasp.org'; 

and in its place i add

export const GRAASP_BUILDER_HOST = 'https://builder.graasp.org'; 
??

**Comment by pyphilia** [comment]
resolved in https://github.com/graasp/graasp-library/pull/212
