### ISSUE TITLE
add banner in landing page

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-library#193]
Add a banner from Unsplash (cite in footer) on the top of the landing page. This banner should include inside the text:

H1: Graasp Library
H2: Browse and Discover Open Educational Resources

And then a big search bar in the middle.

Underneath, the title "Graasp Selection" should be changed to "Featured Collections"

<img width="1425" alt="Screenshot 2022-10-13 at 15 27 37" src="https://user-images.githubusercontent.com/1707188/195610259-d368c3d2-23f0-4f24-828c-609177398345.png">

Similar idea: https://ieeexplore.ieee.org/Xplore/home.jsp

Nice to have: change banner randomly from a selection of photos.

**Comment by juancarlosfarah** [comment]
Tagging @pyphilia and @spaenleh for their awareness.

**Comment by juancarlosfarah** [comment]
Possible Unsplash photos: [this one](https://unsplash.com/photos/Y7d265_7i08) or [this one](https://unsplash.com/photos/FKqxZ58bVjU) or [this one](https://unsplash.com/photos/bByhWydZLW0)).

**Comment by dialexo** [comment]
Given the new design, do we still plan on adding this? Not sure if it fits well anymore @juancarlosfarah in which case we can close this

**Comment by dialexo** [comment]
> @dialexo, as far as I can see in library.graasp.org, I still think we can do something to improve the landing page. Do we have an idea of what we want it to look like?

@juancarlosfarah no this is not the final design, it is still in #275. Here's a screenshot:

![image](https://github.com/graasp/graasp-library/assets/14943421/1c22f5dc-b4f3-431e-b759-cc284279465f)

**Comment by juancarlosfarah** [comment]
Nice. This looks good! My only suggestion is that there is too much blue there. Especially in the top. the blue should be replaced by either an image from unsplash.com or a drawing / repeating pattern. Whatever is easiest.

Let's close when #275 is deployed to production.

**Comment by spaenleh** [comment]
Deployed to production.
