### ISSUE TITLE
Rework Homepage Display / Layout / Content

### ISSUE THREAD

**Issue by clementcharmillot** [graasp/graasp-library#252]
Rework the homepage design.

### Current Mockups

![HomePage](https://user-images.githubusercontent.com/100228798/233856926-015278df-200a-4cc0-9255-546403615253.png)

![image](https://github.com/graasp/graasp-library/assets/100228798/2f6d2cce-a371-4a73-b867-0fd5a72a1c87)

**Comment by dialexo** [comment]
> I am guessing this is to let users click on the whole card to navigate ? 
> Wouldn't it be "easier" to wrap the Card in a `CardActionArea` so the main part of the card is clickable ? See [the Mui documentation](https://mui.com/material-ui/react-card/#primary-action) relative to this example (second one, with options detached)

_Originally posted by @spaenleh in https://github.com/graasp/graasp-library/pull/234#discussion_r1165447594_

**Comment by spaenleh** [comment]
Changes applied in #275
