### ISSUE TITLE
Breadcrumbs are only shown when user is logged in and has a membership on item

### ISSUE THREAD

**Issue by spaenleh** [graasp/graasp-library#258]
To get the rbeadcrumbs of the item in the summary view, we call `useItemTags` hook. This hook fails if the user is logged out or does not have a membership on the item.

It looks like there is no fallback to public for this call.

The impact of this issue is that breadcrumbs are not really shown to users.

**Comment by dialexo** [comment]
I think we cannot fix this until the back-end is stabilized. If I'm not mistaken there is no way to check what is the root published parent without authentication.

**Comment by spaenleh** [comment]
Fixed
