### ISSUE TITLE
[public profile] description loads infinitely

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp-library#544]
My current profile is private, but I can access it on Library. However my description loads infinitely (I suppose all other fields as well). 
I think we should add a banner alert to highlight the fact that one can see their own profile (since they are logged in) but this is still private.

<img width="1398" alt="Screenshot 2024-03-05 at 09 44 21" src="https://github.com/graasp/graasp-library/assets/11229627/7addec18-08bf-4484-a4d9-14a2d74f7563">

**Comment by spaenleh** [comment]
fixed in #565
